metricbeat:
  config:
    modules:
      path: ${path.config}/modules.d/*.yml
      reload:
        enabled: false
        period: 10s

output:
  elasticsearch:
    hosts:
    - elasticsearch_data_node_1:9200
    - elasticsearch_data_node_2:9200
    protocol: http
    username: elastic
    password: password
